# Astir Voice Assistant Configuration
# Default configuration with Annmarie Nele as the young, sultry voice

# Audio Configuration
audio:
  input:
    device_index: -1  # Default input device
    sample_rate: 16000
    chunk_size: 1024
    channels: 1
    format: "int16"
  
  output:
    device_index: -1  # Default output device  
    sample_rate: 22050
    channels: 1
    volume: 0.8

# Speech Recognition (Whisper STT)
speech_recognition:
  model_name: "base"  # Whisper model: tiny, base, small, medium, large
  device: "auto"      # auto, cpu, cuda
  language: "en"      # Auto-detect if null
  temperature: 0.0
  
# Speech Synthesis (Coqui TTS)
speech_synthesis:
  model_name: "tts_models/multilingual/multi-dataset/xtts_v2"
  device: "auto"      # auto, cpu, cuda
  default_voice_id: "annmarie_nele"  # Young, sultry, sophisticated voice
  language: "en"
  sample_rate: 22050
  
  # Voice parameters for sultry, seductive speech
  voice_parameters:
    speaking_rate: 0.9    # Slightly slower for sultry delivery
    pitch: -0.1          # Slightly lower pitch for mature, sexy sound
    volume: 0.8          # Smooth, intimate volume
    energy: 0.8          # Controlled energy for sophisticated delivery

# AI Conversation (OpenRouter)
ai:
  provider: "openrouter"
  model: "anthropic/claude-3.5-sonnet"
  api_key: "${OPENROUTER_API_KEY}"
  max_tokens: 150
  temperature: 0.7
  
  # Personality configuration for young, sultry assistant
  personality:
    style: "sultry"
    tone: "smooth_seductive"
    age_persona: "young_adult"
    traits:
      - "confident"
      - "alluring" 
      - "sophisticated"
      - "charming"
      - "attentive"
    
    # Response style
    response_length: "concise"
    use_contractions: true
    add_sensuality: true
    sophistication_level: "high"

# Conversation Management
conversation:
  max_history_length: 10
  context_window: 4000
  response_timeout: 30
  
  # Natural conversation flow
  interruption_handling: true
  voice_activity_detection: true
  silence_timeout: 3.0
  
  # Sultry, sophisticated conversation style
  conversation_style:
    greeting_style: "alluring"
    farewell_style: "seductive"
    error_handling: "reassuring"
    help_style: "attentive"

# System Configuration  
system:
  log_level: "INFO"
  log_file: "voice_assistant.log"
  max_log_size: "10MB"
  backup_count: 5
  
  # Performance
  enable_gpu: true
  model_cache_size: "2GB"
  
  # Features
  enable_streaming: true
  enable_interruptions: true
  enable_voice_activity_detection: true
