# Astir Voice Assistant Configuration
# Default configuration with Annmarie Nele as the young, sultry voice

# Audio Configuration
audio:
  input:
    device_index: -1  # Default input device
    sample_rate: 16000
    chunk_size: 1024
    channels: 1
    format: "int16"
  
  output:
    device_index: -1  # Default output device  
    sample_rate: 22050
    channels: 1
    volume: 0.8

# Speech Recognition (Enhanced Faster-Whisper STT)
speech_recognition:
  strategy: "faster_whisper"  # Use enhanced faster-whisper strategy
  model_size: "small"         # Upgrade to small for better accuracy (was base)
  device: "cpu"               # cpu, cuda
  compute_type: "int8"        # int8, int16, float16, float32 (int8 for speed)
  recognition_language: "en"  # Language code or "auto" for detection
  
  # Enhanced accuracy settings
  confidence_threshold: 0.6   # Lower threshold for better sensitivity
  beam_size: 5               # Beam search for better accuracy
  best_of: 5                 # Multiple candidates for best results
  
  # Audio preprocessing
  enable_vad: true           # Voice Activity Detection
  vad_threshold: 0.5         # VAD sensitivity
  enable_noise_reduction: true # Basic noise reduction
  
  # Performance settings
  enable_streaming: true     # Enable streaming transcription
  max_segment_length: 30     # Maximum segment length in seconds
  
# Speech Synthesis (Coqui TTS)
speech_synthesis:
  model_name: "tts_models/multilingual/multi-dataset/xtts_v2"
  device: "auto"      # auto, cpu, cuda
  default_voice_id: "annmarie_nele"  # Young, sultry, sophisticated voice
  language: "en"
  sample_rate: 22050
  
  # Voice parameters for sultry, seductive speech
  voice_parameters:
    speaking_rate: 0.9    # Slightly slower for sultry delivery
    pitch: -0.1          # Slightly lower pitch for mature, sexy sound
    volume: 0.8          # Smooth, intimate volume
    energy: 0.8          # Controlled energy for sophisticated delivery

# AI Conversation (OpenRouter) - Optimized for Speed
ai:
  provider: "openrouter"
  model: "anthropic/claude-3.5-sonnet"
  api_key: "${OPENROUTER_API_KEY}"
  max_tokens: 100                # Reduced for faster responses
  temperature: 0.7
  
  # Performance optimizations
  enable_streaming: true         # Enable streaming for faster first token
  timeout_seconds: 15           # Reduced timeout for faster failures
  
  # Smart model selection (future enhancement)
  fast_model: "anthropic/claude-3-haiku"  # Faster model for simple queries
  quality_model: "anthropic/claude-3.5-sonnet"  # High-quality model for complex queries
  
  # Context optimization
  max_context_turns: 8          # Reduced context for faster processing
  smart_context_truncation: true # Intelligent context management
  
  # Personality configuration for young, sultry assistant
  personality:
    style: "sultry"
    tone: "smooth_seductive"
    age_persona: "young_adult"
    traits:
      - "confident"
      - "alluring" 
      - "sophisticated"
      - "charming"
      - "attentive"
    
    # Response style
    response_length: "concise"
    use_contractions: true
    add_sensuality: true
    sophistication_level: "high"

# Conversation Management
conversation:
  max_history_length: 10
  context_window: 4000
  response_timeout: 30
  
  # Natural conversation flow
  interruption_handling: true
  voice_activity_detection: true
  silence_timeout: 3.0
  
  # Sultry, sophisticated conversation style
  conversation_style:
    greeting_style: "alluring"
    farewell_style: "seductive"
    error_handling: "reassuring"
    help_style: "attentive"

# System Configuration  
system:
  log_level: "INFO"
  log_file: "voice_assistant.log"
  max_log_size: "10MB"
  backup_count: 5
  
  # Performance
  enable_gpu: true
  model_cache_size: "2GB"
  
  # Features
  enable_streaming: true
  enable_interruptions: true
  enable_voice_activity_detection: true
